### ISSUE TITLE
Help!  I am new to Github

### ISSUE THREAD

**Issue by JoWilliams-NOAA** [nmfs-openscapes/2022-noaa-sefsc-fall#19]
**_HELP!_**  I feel so lost.  I am new to GitHub.
Can you help me?  @KathyFoley-NOAA 
Do you think we are doing this right?

- [x] Yes
- [ ] No

**Comment by amybrossard** [comment]
You got farther than I did Kathy!  I have no idea how to add those checkboxes!

**Comment by KathyFoley-NOAA** [comment]
Nice job, Jo!
