### ISSUE TITLE
Today's exercise

### ISSUE THREAD

**Issue by JoWilliams-NOAA** [nmfs-openscapes/2022-noaa-sefsc-fall#27]
**Hi @KimberleyJohnson-NOAA !**

You missed today's class, so I am helping you catch up!  Did you get this?

- [x] Yes
- [ ] No

Can you comment and close the issue?

- [x] Yes
- [ ] No

Now, do this:

- Create a new issue and tag and assign me.

Jo

**Comment by KimberleyJohnson-NOAA** [comment]
Interest class assignment.  Let's see if I can figure it out.
